global:
  slack_api_url: "https://hooks.slack.com/services/SlackAPI"
route:
  group_by: ['instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
  - match:
      alertname: "high_load"
  receiver: 'slack'
receivers:
- name: 'slack'
  slack_configs:
  - channel: "#prom-graf-than"
    text: "summary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"