version: "3.7"

volumes:
  prometheus1_vol: {}
  prometheus2_vol: {}
  grafana_data: {}

services:
  prometheus1:
    image: prom/prometheus:v2.14.0
    volumes:
      - ./prometheus/:/etc/prometheus
      - prometheus1_vol:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus1.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.max-block-duration=2h'
      - '--storage.tsdb.min-block-duration=2h'
      - '--web.enable-lifecycle'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9081:9090
    restart: always

  prometheus2:
    image: prom/prometheus:v2.14.0
    volumes:
      - ./prometheus/:/etc/prometheus
      - prometheus1_vol:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus2.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.max-block-duration=2h'
      - '--storage.tsdb.min-block-duration=2h'
      - '--web.enable-lifecycle'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9082:9090
    restart: always
  node-exporter:
    image: prom/node-exporter:v0.18.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always

  grafana:
    image: grafana/grafana:6.4.4
    user: "104"
    depends_on:
      - prometheus-1
      - prometheus-2
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always