apiVersion: 1
deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
- name: Thanos
  type: prometheus
  access: proxy
  orgId: 1
  url: http://docker-compose_prom_querier_1:10902
  isDefault: true
  editable: true

  - name: InfluxDB
    type: influxdb
    access: proxy
    database: influxdb_db
    user: admin
    url: http://docker-compose_prom_influxdb_1:8086
    jsonData:
      httpMode: GET
    secureJsonData:
      password: password
    editable: true